package View;

import java.awt.Component;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nanang M32
 */
public class LaporanPembayaran extends javax.swing.JPanel {
    private int totalPages;
    private DefaultTableModel tabmode;
    private final Connection conn;
    private Component rootPane;

    private Map<String, Object> parameter;
    String semester;
    String thnmasuk;
    String kelas;
    public LaporanPembayaran() {
        initComponents();
        
        
        conn = koneksi.getConnection();
        setTabelModel();
        loadData();

    }
    private void setTabelModel() {
        
        Object[] Baris ={"Kode Pembayaran","ID Santri","NISN","Nama","Kelas","Juli","Agustus","September","Oktober","November","Desember",
            "Januari","Februari","Maret","April","Mei","Juni","Daftar Ulang","Ujian","Total","Tanggal"};
 tabmode = new DefaultTableModel(null, Baris);
 
        try {
        String sql = "SELECT * FROM pembayaran ";
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
        tabmode.addRow(new Object[]{
        hasil.getString(1),
        hasil.getString(2),
        hasil.getString(3),
        hasil.getString(4),
        hasil.getString(5),
        hasil.getString(6),
        hasil.getString(7),
        hasil.getString(8),
        hasil.getString(9),
        hasil.getString(10),
        hasil.getString(11),
        hasil.getString(12),
        hasil.getString(13),
        hasil.getString(14),
        hasil.getString(15),
        hasil.getString(16),
        hasil.getString(17),
        hasil.getString(18),
        hasil.getString(19),
        hasil.getString(20),
        hasil.getString(21),
        });
        }
        tblpembayaran.setModel(tabmode);
        } catch (SQLException e) {
            
        }
        
    }

    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        
    try {
    String sql ="SELECT * FROM pembayaran";
    try (PreparedStatement st = conn.prepareStatement(sql)){
        ResultSet rs = st.executeQuery();
        
        while (rs.next()){
            String KodePembayaran = rs.getString("kodetransaksi");
            String IDSantri = rs.getString("idsantri");
            String NisnSiswa = rs.getString("nisn");
            String NamaSiswa = rs.getString("nama");
            String Kelas = rs.getString("kelas");
            String SPP = rs.getString("spp");
            String SPP2 = rs.getString("spp2");
            String SPP3 = rs.getString("spp3");
            String SPP4 = rs.getString("spp4");
            String SPP5 = rs.getString("spp5");
            String SPP6 = rs.getString("spp6");
            String SPP7 = rs.getString("spp7");
            String SPP8 = rs.getString("spp8");
            String SPP9 = rs.getString("spp9");
            String SPP10 = rs.getString("spp10");
            String SPP11 = rs.getString("spp11");
            String SPP12 = rs.getString("spp12");
            String DaftarUlang = rs.getString("daftarulang");
            String Ujian = rs.getString("ujian");
            String Total = rs.getString("total");
            Date Tanggal = rs.getDate("tanggal");
            
            Object[] Baris ={KodePembayaran,IDSantri,NisnSiswa,NamaSiswa,Kelas,SPP,SPP2,SPP3,SPP4,SPP5,SPP6
                    ,SPP7,SPP8,SPP9,SPP10,SPP11,SPP12,DaftarUlang,Ujian,Total,Tanggal};
            model.addRow(Baris);
        }
       }
     } catch (SQLException e){
            Logger.getLogger(MenuPembayaran.class.getName()).log(Level.SEVERE,null,e);
        }
    }
  private void loadData() {
        getData((DefaultTableModel) tblpembayaran.getModel());

    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbjeniskelamin = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Bcetak = new fosalgo.CARI();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpembayaran = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        bcari = new fosalgo.CARI();
        jLabel6 = new javax.swing.JLabel();
        jtanggal = new javax.swing.JSpinner();
        jtanggal2 = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(1026, 716));
        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("CETAK LAPORAN PEMBAYARAN");

        Bcetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        Bcetak.setText("Cetak Pembayaran ");
        Bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcetakActionPerformed(evt);
            }
        });

        tblpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tblpembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpembayaran);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TANGGAL");

        bcari.setText("View");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("s/d");

        jtanggal.setModel(new javax.swing.SpinnerDateModel());
        jtanggal.setRequestFocusEnabled(false);

        jtanggal2.setModel(new javax.swing.SpinnerDateModel());
        jtanggal2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel6))
                            .addComponent(Bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(487, Short.MAX_VALUE))
            .addGroup(panelViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(Bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelMain.add(panelView, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcetakActionPerformed
        try {
            String path="src/Report/pembayaran.jasper";      // letak penyimpanan report
            HashMap parameter = new HashMap();
            parameter.put("tgl1",jtanggal.getValue());
            parameter.put("tgl2",jtanggal2.getValue());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print,false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_BcetakActionPerformed

    private void tblpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpembayaranMouseClicked
       
    }//GEN-LAST:event_tblpembayaranMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed

    }//GEN-LAST:event_bcariActionPerformed

    private void showPanel(){
        panelMain.removeAll();
        panelMain.add(new LaporanPembayaran());
        panelMain.repaint();
        panelMain.revalidate();
    }
   
     private void searchData() {
        String kataKunci = jtanggal.getName();
        String kataKunci2 = jtanggal2.getName();
        
        DefaultTableModel model = (DefaultTableModel) tblpembayaran.getModel();
        model.setRowCount(0);
        
    try {
    String sql ="SELECT * FROM pembayaran WHERE tanggal LIKE ?";
    try (PreparedStatement st = conn.prepareStatement(sql)){
        st.setString(1,"%" + kataKunci + "%");
        st.setString(2,"%" + kataKunci2 + "%");
        ResultSet rs = st.executeQuery();
        
        while (rs.next()){
            String KodePembayaran = rs.getString("kodetransaksi");
            String IDSantri = rs.getString("idsantri");
            String NisnSiswa = rs.getString("nisn");
            String NamaSiswa = rs.getString("nama");
            String Kelas = rs.getString("kelas");
            String SPP = rs.getString("spp");
            String SPP2 = rs.getString("spp2");
            String SPP3 = rs.getString("spp3");
            String SPP4 = rs.getString("spp4");
            String SPP5 = rs.getString("spp5");
            String SPP6 = rs.getString("spp6");
            String SPP7 = rs.getString("spp7");
            String SPP8 = rs.getString("spp8");
            String SPP9 = rs.getString("spp9");
            String SPP10 = rs.getString("spp10");
            String SPP11 = rs.getString("spp11");
            String SPP12 = rs.getString("spp12");
            String DaftarUlang = rs.getString("daftarulang");
            String Ujian = rs.getString("ujian");
            String Total = rs.getString("total");
            Date Tanggal = rs.getDate("tanggal");
            
            Object[] Baris ={KodePembayaran,IDSantri,NisnSiswa,NamaSiswa,Kelas,SPP,SPP2,SPP3,SPP4,SPP5,SPP6
                    ,SPP7,SPP8,SPP9,SPP10,SPP11,SPP12,DaftarUlang,Ujian,Total,Tanggal};
            model.addRow(Baris);

        }
       }
     } catch (SQLException e){
            Logger.getLogger(MenuSantri.class.getName()).log(Level.SEVERE,null,e);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fosalgo.CARI Bcetak;
    private fosalgo.CARI bcari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jtanggal;
    private javax.swing.JSpinner jtanggal2;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.ButtonGroup rbjeniskelamin;
    private javax.swing.JTable tblpembayaran;
    // End of variables declaration//GEN-END:variables

}

        
