package View;

import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nanang M32
 */
public class LaporanAlternatif extends javax.swing.JPanel {
    private int totalPages;
    private DefaultTableModel tabmode;
    private final Connection conn;
    private Component rootPane;

    private Map<String, Object> parameter;
    String semester;
    String thnmasuk;
    String kelas;
    public LaporanAlternatif() {
        initComponents();
        
        
        conn = koneksi.getConnection();
        setTabelModel();
        loadData();

    }
 private void setTabelModel() {
        DefaultTableModel model = (DefaultTableModel)tblsiswa.getModel();
        model.addColumn("NISN");
        model.addColumn("Nama Santri");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tempat, Tanggal Lahir");
        model.addColumn("Kelas");
        model.addColumn("Alamat");
        model.addColumn("Orang Tua/ Wali");
        model.addColumn("Tahun Masuk");
        model.addColumn("Semester");
    }
  private void loadData() {
        getData((DefaultTableModel) tblsiswa.getModel());

    }
    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        
    try {
    String sql ="SELECT * FROM santri";
    try (PreparedStatement st = conn.prepareStatement(sql)){
        ResultSet rs = st.executeQuery();
        
        while (rs.next()){
            String NisnSiswa = rs.getString("nisn");
            String NamaSiswa = rs.getString("nama");
            String JenisKelamin = rs.getString("jenisk");
            String TempatTL = rs.getString("ttl");
            String Kelas = rs.getString("kelas");
            String AlamatSiswa = rs.getString("alamat");
            String OrangtuaWali = rs.getString("ortu");
            String Thnmasuk = rs.getString("thnmasuk");
             String Semester = rs.getString("semester");
            
            Object[] Baris ={NisnSiswa,NamaSiswa,JenisKelamin,TempatTL,Kelas,AlamatSiswa,OrangtuaWali,Thnmasuk,Semester};
            model.addRow(Baris);
        }
       }
     } catch (SQLException e){
            Logger.getLogger(MenuSantri.class.getName()).log(Level.SEVERE,null,e);
        }
    }    
    private void searchData() {
        String kataKunci = txtkelas.getText();
        
        DefaultTableModel model = (DefaultTableModel) tblsiswa.getModel();
        model.setRowCount(0);
        
    try {
    String sql ="SELECT * FROM santri WHERE kelas LIKE ?";
    try (PreparedStatement st = conn.prepareStatement(sql)){
        st.setString(1,"%" + kataKunci + "%");
        ResultSet rs = st.executeQuery();
        
        while (rs.next()){
          String NisnSiswa = rs.getString("nisn");
            String NamaSiswa = rs.getString("nama");
            String JenisKelamin = rs.getString("jenisk");
            String TempatTL = rs.getString("ttl");
            String Kelas = rs.getString("kelas");
            String AlamatSiswa = rs.getString("alamat");
            String OrangtuaWali = rs.getString("ortu");
            String Thnmasuk = rs.getString("thnmasuk");
             String Semester = rs.getString("semester");
            
            Object[] Baris ={NisnSiswa,NamaSiswa,JenisKelamin,TempatTL,Kelas,AlamatSiswa,OrangtuaWali,Thnmasuk,Semester};
            model.addRow(Baris);
        }
       }
     } catch (SQLException e){
            Logger.getLogger(MenuSantri.class.getName()).log(Level.SEVERE,null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbjeniskelamin = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cETAK2 = new fosalgo.CETAK();
        Bcetak = new fosalgo.CARI();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsiswa = new javax.swing.JTable();
        txtkelas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttahun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsemester = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bcari = new fosalgo.CARI();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(1026, 716));
        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("1.Laporan Santri Berdasarkan Kelas");

        cETAK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        cETAK2.setText("CETAK SEMUA DATA");
        cETAK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cETAK2ActionPerformed(evt);
            }
        });

        Bcetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        Bcetak.setText("Cetak Data Perkelas");
        Bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcetakActionPerformed(evt);
            }
        });

        tblsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tblsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsiswa);

        txtkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkelasActionPerformed(evt);
            }
        });

        jLabel2.setText("Kelas");

        jLabel3.setText("Tahun");

        jLabel4.setText("Semester");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("2.Laporan Semua Data Santri");

        bcari.setText("cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Bcetak, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtkelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(txttahun, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtsemester, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(45, 45, 45)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cETAK2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cETAK2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtsemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(Bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        panelMain.add(panelView, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void cETAK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cETAK2ActionPerformed
        try {
            String path="src/Report/report7.jasper";
            JasperPrint jp = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            Component rootPane = null;
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_cETAK2ActionPerformed

    private void BcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcetakActionPerformed
        try {
            String path="src/Report/report4.jasper";      // letak penyimpanan report
            HashMap parameter = new HashMap();
            parameter.put("kelas",txtkelas.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print,false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_BcetakActionPerformed

    private void tblsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsiswaMouseClicked
       
    }//GEN-LAST:event_tblsiswaMouseClicked

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        popupLPsiswa Pp = new popupLPsiswa();
        Pp.santrilp = this;
        Pp.setVisible(true);
        Pp.setResizable(false);
    }//GEN-LAST:event_bcariActionPerformed

    private void txtkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkelasActionPerformed
        searchData();
    }//GEN-LAST:event_txtkelasActionPerformed
public void itemTerpilih(){
    popupLPsiswa Pp = new popupLPsiswa();
    Pp.santrilp = this;
    txtkelas.setText(kelas);
    txttahun.setText(thnmasuk);
    txtsemester.setText(semester);
}
    private void showPanel(){
        panelMain.removeAll();
        panelMain.add(new LaporanAlternatif());
        panelMain.repaint();
        panelMain.revalidate();
    }
   
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fosalgo.CARI Bcetak;
    private fosalgo.CARI bcari;
    private fosalgo.CETAK cETAK2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.ButtonGroup rbjeniskelamin;
    private javax.swing.JTable tblsiswa;
    private javax.swing.JTextField txtkelas;
    private javax.swing.JTextField txtsemester;
    private javax.swing.JTextField txttahun;
    // End of variables declaration//GEN-END:variables

}

        
