package View;

import java.awt.Component;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nanang M32
 */
public class MenuPembayaran extends javax.swing.JPanel {
    private int totalPages;
    private DefaultTableModel tabmode;
    private final Connection conn;
    private Component rootPane;
    String idsantri;
    String nisn;
    String nama;
    String kelas;
    public MenuPembayaran() {
        initComponents();
        
        
        conn = koneksi.getConnection();
        setTabelModel();
        loadData();
    }

public void itemTerpilih(){
    popupsantri Pp = new popupsantri();
    Pp.santri = this;
    txtidsantri.setText(idsantri);
    txtnisn.setText(nisn);
    txtnama.setText(nama);
    txtkelas.setText(kelas);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbjeniskelamin = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        panelView = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpembayaran = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bthapus = new fosalgo.FButtonHapus();
        btTambah = new fosalgo.FButtonTambah();
        bBatal = new fosalgo.BATAL();
        txtidsantri = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtnisn = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtkelas = new javax.swing.JTextField();
        txtspp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtdaftarulang = new javax.swing.JTextField();
        txtujian = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jtanggal = new javax.swing.JSpinner();
        jLabel23 = new javax.swing.JLabel();
        bcari = new fosalgo.CARI();
        jLabel24 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        Bcetak = new fosalgo.CARI();
        txtspp1 = new javax.swing.JTextField();
        txtspp2 = new javax.swing.JTextField();
        txtspp3 = new javax.swing.JTextField();
        txtspp4 = new javax.swing.JTextField();
        txtspp5 = new javax.swing.JTextField();
        txtspp6 = new javax.swing.JTextField();
        txtspp7 = new javax.swing.JTextField();
        txtspp8 = new javax.swing.JTextField();
        txtspp9 = new javax.swing.JTextField();
        txtspp10 = new javax.swing.JTextField();
        txtspp11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 153));
        setPreferredSize(new java.awt.Dimension(1026, 716));
        setLayout(new java.awt.CardLayout());

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setLayout(new java.awt.CardLayout());

        panelView.setBackground(new java.awt.Color(255, 255, 255));

        tbpembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tbpembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpembayaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbpembayaran);
        tbpembayaran.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("Pembayaran Santri");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MacBook Money.png"))); // NOI18N

        bthapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cancel_1.png"))); // NOI18N
        bthapus.setText("HAPUS");
        bthapus.setFillOver(new java.awt.Color(255, 51, 0));
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add.png"))); // NOI18N
        btTambah.setText("SIMPAN");
        btTambah.setFillClick(new java.awt.Color(0, 153, 153));
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        bBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Go Back.png"))); // NOI18N
        bBatal.setText("BATAL");
        bBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBatalActionPerformed(evt);
            }
        });

        txtidsantri.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel15.setText("ID Santri");

        txtnisn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel16.setText("NISN");

        txtnama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel17.setText("Nama");

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel18.setText("Kelas");

        txtkelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        txtspp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsppActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel19.setText("SPP BULANAN");

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel20.setText("Daftar Ulang");

        txtdaftarulang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtdaftarulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdaftarulangActionPerformed(evt);
            }
        });

        txtujian.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtujian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtujianActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel21.setText("Ujian UTS & UAS");

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel22.setText("Total Pembayaran");

        txttotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        jtanggal.setModel(new javax.swing.SpinnerDateModel());
        jtanggal.setRequestFocusEnabled(false);

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel23.setText("Tanggal");

        bcari.setText("cari");
        bcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcariActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel24.setText("Kode Pembayaran");

        txtkode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));

        Bcetak.setText("Slip ");
        Bcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcetakActionPerformed(evt);
            }
        });

        txtspp1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp1ActionPerformed(evt);
            }
        });

        txtspp2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp2ActionPerformed(evt);
            }
        });

        txtspp3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp3ActionPerformed(evt);
            }
        });

        txtspp4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp4ActionPerformed(evt);
            }
        });

        txtspp5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp5ActionPerformed(evt);
            }
        });

        txtspp6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp6ActionPerformed(evt);
            }
        });

        txtspp7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp7ActionPerformed(evt);
            }
        });

        txtspp8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp8ActionPerformed(evt);
            }
        });

        txtspp9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp9ActionPerformed(evt);
            }
        });

        txtspp10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp10ActionPerformed(evt);
            }
        });

        txtspp11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 0)));
        txtspp11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspp11ActionPerformed(evt);
            }
        });

        jLabel2.setText("Juli");

        jLabel4.setText("Agustus");

        jLabel5.setText("September");

        jLabel6.setText("Oktober");

        jLabel7.setText("November");

        jLabel8.setText("Desember");

        jLabel9.setText("Januari");

        jLabel10.setText("Februari");

        jLabel11.setText("Maret");

        jLabel12.setText("April");

        jLabel13.setText("Mei");

        jLabel14.setText("Juni");

        javax.swing.GroupLayout panelViewLayout = new javax.swing.GroupLayout(panelView);
        panelView.setLayout(panelViewLayout);
        panelViewLayout.setHorizontalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(txtnisn)
                            .addComponent(txtnama)
                            .addComponent(txtkelas)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15)
                            .addComponent(jLabel24)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(txtidsantri, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bcari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelViewLayout.createSequentialGroup()
                                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtspp)
                                            .addComponent(txtspp1)
                                            .addComponent(txtspp2)
                                            .addComponent(txtspp3)
                                            .addComponent(txtspp4)
                                            .addComponent(txtspp5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(23, 23, 23)
                                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtspp6)
                                            .addComponent(txtspp7)
                                            .addComponent(txtspp8)
                                            .addComponent(txtspp9)
                                            .addComponent(txtspp10)
                                            .addComponent(txtspp11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelViewLayout.createSequentialGroup()
                                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelViewLayout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel21)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel22))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelViewLayout.createSequentialGroup()
                                                .addComponent(txtdaftarulang, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtujian, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(133, 133, 133))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(btTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelViewLayout.setVerticalGroup(
            panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelViewLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bcetak, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(5, 5, 5)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtspp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(5, 5, 5)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtspp1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(5, 5, 5)
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtspp2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(5, 5, 5)
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtspp3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(5, 5, 5)
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtspp4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(5, 5, 5)
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtspp5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtdaftarulang, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtujian, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelViewLayout.createSequentialGroup()
                                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtidsantri, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bcari, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnisn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addGap(13, 13, 13)
                                .addComponent(txtkelas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelViewLayout.createSequentialGroup()
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtspp6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(5, 5, 5)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtspp7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(5, 5, 5)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtspp8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(5, 5, 5)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtspp9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(5, 5, 5)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtspp10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(5, 5, 5)
                        .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtspp11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(76, 76, 76)))
                .addGroup(panelViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bthapus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelMain.add(panelView, "card2");

        add(panelMain, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void bcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcariActionPerformed
        popupsantri Pp = new popupsantri();
        Pp.santri = this;
        Pp.setVisible(true);
        Pp.setResizable(false);

    }//GEN-LAST:event_bcariActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed

    }//GEN-LAST:event_txttotalActionPerformed

    private void txtujianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtujianActionPerformed
        int SPP,SPP1,SPP2,SPP3,SPP4,SPP5,SPP6,SPP7,SPP8,SPP9,SPP10,SPP11,DaftarUlang,Ujian,Total;
        SPP=Integer.parseInt(txtspp.getText());
        SPP1=Integer.parseInt(txtspp1.getText());
        SPP2=Integer.parseInt(txtspp2.getText());
        SPP3=Integer.parseInt(txtspp3.getText());
        SPP4=Integer.parseInt(txtspp4.getText());
        SPP5=Integer.parseInt(txtspp5.getText());
        SPP6=Integer.parseInt(txtspp6.getText());
        SPP7=Integer.parseInt(txtspp7.getText());
        SPP8=Integer.parseInt(txtspp8.getText());
        SPP9=Integer.parseInt(txtspp9.getText());
        SPP10=Integer.parseInt(txtspp10.getText());
        SPP11=Integer.parseInt(txtspp11.getText());
        DaftarUlang=Integer.parseInt(txtdaftarulang.getText());
        Ujian=Integer.parseInt(txtujian.getText());
        Total=SPP+SPP1+SPP2+SPP3+SPP4+SPP5+SPP6+SPP7+SPP8+SPP9+SPP10+SPP11+DaftarUlang+Ujian;
        txttotal.setText(String.valueOf(Total));
    }//GEN-LAST:event_txtujianActionPerformed

    private void txtdaftarulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdaftarulangActionPerformed

    }//GEN-LAST:event_txtdaftarulangActionPerformed

    private void txtsppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsppActionPerformed

    private void bBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBatalActionPerformed
        showPanel();
        loadData();
    }//GEN-LAST:event_bBatalActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        insertData();
    }//GEN-LAST:event_btTambahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        deletData();
    }//GEN-LAST:event_bthapusActionPerformed

    private void tbpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpembayaranMouseClicked
        int bar = tbpembayaran.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        txtkode.setText(a);
        bthapus.setVisible(true);
        bBatal.setVisible(true);
    }//GEN-LAST:event_tbpembayaranMouseClicked

    private void BcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcetakActionPerformed
        try {
            String path="src/Report/report5.jasper";      // letak penyimpanan report
            HashMap parameter = new HashMap();
            parameter.put("kode",txtkode.getText());
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print,false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_BcetakActionPerformed

    private void txtspp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp1ActionPerformed

    private void txtspp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp2ActionPerformed

    private void txtspp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp3ActionPerformed

    private void txtspp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp4ActionPerformed

    private void txtspp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp5ActionPerformed

    private void txtspp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp6ActionPerformed

    private void txtspp7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp7ActionPerformed

    private void txtspp8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp8ActionPerformed

    private void txtspp9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp9ActionPerformed

    private void txtspp10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp10ActionPerformed

    private void txtspp11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspp11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspp11ActionPerformed
 private void loadData() {
        getData((DefaultTableModel) tbpembayaran.getModel());
        bthapus.setVisible(false);
        bBatal.setVisible(false);
    }
    
    private void showPanel(){
        panelMain.removeAll();
        panelMain.add(new MenuPembayaran());
        panelMain.repaint();
        panelMain.revalidate();
    }
    private void setTabelModel() {
        
        Object[] Baris ={"Kode Pembayaran","ID Santri","NISN","Nama","Kelas","Juli","Agustus","September","Oktober","November","Desember",
            "Januari","Februari","Maret","April","Mei","Juni","Daftar Ulang","Ujian","Total","Tanggal"};
 tabmode = new DefaultTableModel(null, Baris);
 
        try {
        String sql = "SELECT * FROM pembayaran ";
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
        tabmode.addRow(new Object[]{
        hasil.getString(1),
        hasil.getString(2),
        hasil.getString(3),
        hasil.getString(4),
        hasil.getString(5),
        hasil.getString(6),
        hasil.getString(7),
        hasil.getString(8),
        hasil.getString(9),
        hasil.getString(10),
        hasil.getString(11),
        hasil.getString(12),
        hasil.getString(13),
        hasil.getString(14),
        hasil.getString(15),
        hasil.getString(16),
        hasil.getString(17),
        hasil.getString(18),
        hasil.getString(19),
        hasil.getString(20),
        hasil.getString(21),
        });
        }
        tbpembayaran.setModel(tabmode);
        } catch (SQLException e) {
            
        }
        
    }

    private void getData(DefaultTableModel model) {
        model.setRowCount(0);
        
    try {
    String sql ="SELECT * FROM pembayaran";
    try (PreparedStatement st = conn.prepareStatement(sql)){
        ResultSet rs = st.executeQuery();
        
        while (rs.next()){
            String KodePembayaran = rs.getString("kodetransaksi");
            String IDSantri = rs.getString("idsantri");
            String NisnSiswa = rs.getString("nisn");
            String NamaSiswa = rs.getString("nama");
            String Kelas = rs.getString("kelas");
            String SPP = rs.getString("spp");
            String SPP2 = rs.getString("spp2");
            String SPP3 = rs.getString("spp3");
            String SPP4 = rs.getString("spp4");
            String SPP5 = rs.getString("spp5");
            String SPP6 = rs.getString("spp6");
            String SPP7 = rs.getString("spp7");
            String SPP8 = rs.getString("spp8");
            String SPP9 = rs.getString("spp9");
            String SPP10 = rs.getString("spp10");
            String SPP11 = rs.getString("spp11");
            String SPP12 = rs.getString("spp12");
            String DaftarUlang = rs.getString("daftarulang");
            String Ujian = rs.getString("ujian");
            String Total = rs.getString("total");
            Date Tanggal = rs.getDate("tanggal");
            
            Object[] Baris ={KodePembayaran,IDSantri,NisnSiswa,NamaSiswa,Kelas,SPP,SPP2,SPP3,SPP4,SPP5,SPP6
                    ,SPP7,SPP8,SPP9,SPP10,SPP11,SPP12,DaftarUlang,Ujian,Total,Tanggal};
            model.addRow(Baris);
        }
       }
     } catch (SQLException e){
            Logger.getLogger(MenuPembayaran.class.getName()).log(Level.SEVERE,null,e);
        }
    }    

    private void insertData() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        String tanggal = sdf.format(jtanggal.getValue());
        String sql = "insert into pembayaran  values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"; 
        try{

        PreparedStatement stat = conn.prepareStatement(sql);
        stat.setString(1, txtkode.getText());
        stat.setString(2, txtidsantri.getText());
        stat.setString(3, txtnisn.getText());
        stat.setString(4, txtnama.getText());
        stat.setString(5, txtkelas.getText());
        stat.setString(6, txtspp.getText());
        stat.setString(7, txtspp1.getText());
        stat.setString(8, txtspp2.getText());
        stat.setString(9, txtspp3.getText());
        stat.setString(10, txtspp4.getText());
        stat.setString(11, txtspp5.getText());
        stat.setString(12, txtspp6.getText());
        stat.setString(13, txtspp7.getText());
        stat.setString(14, txtspp8.getText());
        stat.setString(15, txtspp9.getText());
        stat.setString(16, txtspp10.getText());
        stat.setString(17, txtspp11.getText());
        stat.setString(18, txtdaftarulang.getText());
        stat.setString(19, txtujian.getText());
        stat.setString(20, txttotal.getText());
        stat.setString(21, tanggal);
        stat.executeUpdate();

        int t = tbpembayaran.getRowCount();
        for(int i=0; i < t ; i++)
        {
        String SPP = tbpembayaran.getValueAt(i, 0).toString();
        String SPP2 = tbpembayaran.getValueAt(i, 1).toString();
        String SPP3 = tbpembayaran.getValueAt(i, 2).toString();
            String SPP4 = tbpembayaran.getValueAt(i, 3).toString();
            String SPP5 = tbpembayaran.getValueAt(i, 4).toString();
            String SPP6 = tbpembayaran.getValueAt(i, 5).toString();
            String SPP7 = tbpembayaran.getValueAt(i, 6).toString();
            String SPP8 = tbpembayaran.getValueAt(i, 7).toString();
            String SPP9 = tbpembayaran.getValueAt(i, 8).toString();
            String SPP10 = tbpembayaran.getValueAt(i, 9).toString();
            String SPP11 = tbpembayaran.getValueAt(i, 10).toString();
            String SPP12 = tbpembayaran.getValueAt(i, 11).toString();
        String daftarulang = tbpembayaran.getValueAt(i, 12).toString();
        String ujian = tbpembayaran.getValueAt(i, 13).toString();
        String total = tbpembayaran.getValueAt(i, 14).toString();

        
        }
        JOptionPane.showMessageDialog(null, "data berhasil disimpan");
        }
        catch (SQLException e){
        JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        
        loadData();
        showPanel();
       
    }
public void hitung(){
    int total = 0;
    for (int i = 0; i < tbpembayaran.getRowCount(); i++) {
        try {
            // Pastikan nilai yang dibaca adalah angka yang valid
            int amount = Integer.parseInt(tbpembayaran.getValueAt(i, 3).toString());
            total += amount;
        } catch (NumberFormatException e) {
            // Jika ada nilai yang tidak dapat diubah menjadi angka, abaikan atau beri pesan error
            JOptionPane.showMessageDialog(null, "Ada data yang tidak valid di baris: " + (i+1));
        }
    }
    txttotal.setText(Integer.toString(total)); // Menampilkan total yang dihitung
 }
    private void deletData() {
     int selecteRow = tbpembayaran.getSelectedRow();
     int confirm = JOptionPane.showConfirmDialog(this, "Apakah yakin ingin menghapus data ini ?",
             "Konfirmasi Hapus Data",JOptionPane.YES_NO_OPTION);
     if (confirm == JOptionPane.YES_OPTION){
         String id = tbpembayaran.getValueAt(selecteRow, 0).toString();
         try{
             String sql = "DELETE FROM pembayaran WHERE kodetransaksi=?";
             try(PreparedStatement st = conn.prepareStatement(sql)){
                 st.setString(1, id);
                 
                 int rowDeleted = st.executeUpdate();
                 if(rowDeleted > 0){
                     JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
                    
                 }else{
                     JOptionPane.showMessageDialog(this, "Data Gagal dihapus");
                 }
             }
         } catch (SQLException e){    
         }
     }

     loadData();
     showPanel();
    }
     
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private fosalgo.CARI Bcetak;
    private fosalgo.BATAL bBatal;
    private fosalgo.CARI bcari;
    private fosalgo.FButtonTambah btTambah;
    private fosalgo.FButtonHapus bthapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jtanggal;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelView;
    private javax.swing.ButtonGroup rbjeniskelamin;
    private javax.swing.JTable tbpembayaran;
    private javax.swing.JTextField txtdaftarulang;
    private javax.swing.JTextField txtidsantri;
    private javax.swing.JTextField txtkelas;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnisn;
    private javax.swing.JTextField txtspp;
    private javax.swing.JTextField txtspp1;
    private javax.swing.JTextField txtspp10;
    private javax.swing.JTextField txtspp11;
    private javax.swing.JTextField txtspp2;
    private javax.swing.JTextField txtspp3;
    private javax.swing.JTextField txtspp4;
    private javax.swing.JTextField txtspp5;
    private javax.swing.JTextField txtspp6;
    private javax.swing.JTextField txtspp7;
    private javax.swing.JTextField txtspp8;
    private javax.swing.JTextField txtspp9;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtujian;
    // End of variables declaration//GEN-END:variables

   
}

        
