/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;
import login.MenuLogin;

/**
 *
 * @author Nanang M32
 */
public class MenuUtamaDS extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtamaDS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_kiri = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pn_main = new javax.swing.JPanel();
        pn_line = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btdashbord = new javax.swing.JLabel();
        pn_santri = new javax.swing.JPanel();
        pn_line1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btsantri = new javax.swing.JLabel();
        pn_ustd = new javax.swing.JPanel();
        pn_line2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btustd = new javax.swing.JLabel();
        pn_kelas = new javax.swing.JPanel();
        pn_line3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btkelas = new javax.swing.JLabel();
        proses = new javax.swing.JLabel();
        pn_pembayaran = new javax.swing.JPanel();
        pn_line5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btpembayaran = new javax.swing.JLabel();
        pn_jadwal = new javax.swing.JPanel();
        pn_line6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btjadwal = new javax.swing.JLabel();
        laporan = new javax.swing.JLabel();
        pn_absen = new javax.swing.JPanel();
        pn_line9 = new javax.swing.JPanel();
        btabsen = new javax.swing.JLabel();
        pn_nilai = new javax.swing.JPanel();
        pn_line10 = new javax.swing.JPanel();
        btnilai = new javax.swing.JLabel();
        pn_keluar = new javax.swing.JPanel();
        pn_line11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btkeluar = new javax.swing.JLabel();
        pn_pemb = new javax.swing.JPanel();
        pn_line12 = new javax.swing.JPanel();
        btnpembayaran = new javax.swing.JLabel();
        pn_kanan = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        pn_dasar = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1566, 768));

        pn_kiri.setBackground(new java.awt.Color(255, 255, 255));
        pn_kiri.setPreferredSize(new java.awt.Dimension(300, 768));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("SIPONPES");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoo.png"))); // NOI18N

        jLabel5.setText("SIstem Informasi Pondok Pesantren");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("MASTER DATA");

        pn_main.setBackground(new java.awt.Color(255, 255, 255));

        pn_line.setBackground(new java.awt.Color(255, 255, 255));
        pn_line.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_lineLayout = new javax.swing.GroupLayout(pn_line);
        pn_line.setLayout(pn_lineLayout);
        pn_lineLayout.setHorizontalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_lineLayout.setVerticalGroup(
            pn_lineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Studio Display.png"))); // NOI18N

        btdashbord.setBackground(new java.awt.Color(255, 255, 255));
        btdashbord.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btdashbord.setForeground(new java.awt.Color(0, 102, 51));
        btdashbord.setText("Dashboard");
        btdashbord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btdashbordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btdashbordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btdashbordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_mainLayout = new javax.swing.GroupLayout(pn_main);
        pn_main.setLayout(pn_mainLayout);
        pn_mainLayout.setHorizontalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(19, 19, 19)
                .addComponent(btdashbord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_mainLayout.setVerticalGroup(
            pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btdashbord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_santri.setBackground(new java.awt.Color(255, 255, 255));

        pn_line1.setBackground(new java.awt.Color(255, 255, 255));
        pn_line1.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line1Layout = new javax.swing.GroupLayout(pn_line1);
        pn_line1.setLayout(pn_line1Layout);
        pn_line1Layout.setHorizontalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line1Layout.setVerticalGroup(
            pn_line1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User Groups_1.png"))); // NOI18N

        btsantri.setBackground(new java.awt.Color(255, 255, 255));
        btsantri.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btsantri.setForeground(new java.awt.Color(0, 102, 51));
        btsantri.setText("Data Santri");
        btsantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsantriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btsantriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btsantriMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_santriLayout = new javax.swing.GroupLayout(pn_santri);
        pn_santri.setLayout(pn_santriLayout);
        pn_santriLayout.setHorizontalGroup(
            pn_santriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_santriLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addComponent(btsantri)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_santriLayout.setVerticalGroup(
            pn_santriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_santriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_santriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btsantri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_ustd.setBackground(new java.awt.Color(255, 255, 255));

        pn_line2.setBackground(new java.awt.Color(255, 255, 255));
        pn_line2.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line2Layout = new javax.swing.GroupLayout(pn_line2);
        pn_line2.setLayout(pn_line2Layout);
        pn_line2Layout.setHorizontalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line2Layout.setVerticalGroup(
            pn_line2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tuition_1.png"))); // NOI18N

        btustd.setBackground(new java.awt.Color(255, 255, 255));
        btustd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btustd.setForeground(new java.awt.Color(0, 102, 51));
        btustd.setText("Data Ustad/z");
        btustd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btustdMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btustdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btustdMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_ustdLayout = new javax.swing.GroupLayout(pn_ustd);
        pn_ustd.setLayout(pn_ustdLayout);
        pn_ustdLayout.setHorizontalGroup(
            pn_ustdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ustdLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(19, 19, 19)
                .addComponent(btustd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_ustdLayout.setVerticalGroup(
            pn_ustdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ustdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_ustdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btustd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_kelas.setBackground(new java.awt.Color(255, 255, 255));

        pn_line3.setBackground(new java.awt.Color(255, 255, 255));
        pn_line3.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line3Layout = new javax.swing.GroupLayout(pn_line3);
        pn_line3.setLayout(pn_line3Layout);
        pn_line3Layout.setHorizontalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line3Layout.setVerticalGroup(
            pn_line3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Google Classroom.png"))); // NOI18N

        btkelas.setBackground(new java.awt.Color(255, 255, 255));
        btkelas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btkelas.setForeground(new java.awt.Color(0, 102, 51));
        btkelas.setText("Data Kelas");
        btkelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btkelasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btkelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btkelasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_kelasLayout = new javax.swing.GroupLayout(pn_kelas);
        pn_kelas.setLayout(pn_kelasLayout);
        pn_kelasLayout.setHorizontalGroup(
            pn_kelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kelasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(19, 19, 19)
                .addComponent(btkelas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_kelasLayout.setVerticalGroup(
            pn_kelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kelasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btkelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        proses.setBackground(new java.awt.Color(255, 255, 255));
        proses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        proses.setText("FORM PROSES");

        pn_pembayaran.setBackground(new java.awt.Color(255, 255, 255));

        pn_line5.setBackground(new java.awt.Color(255, 255, 255));
        pn_line5.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line5Layout = new javax.swing.GroupLayout(pn_line5);
        pn_line5.setLayout(pn_line5Layout);
        pn_line5Layout.setHorizontalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line5Layout.setVerticalGroup(
            pn_line5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MacBook Money.png"))); // NOI18N

        btpembayaran.setBackground(new java.awt.Color(255, 255, 255));
        btpembayaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btpembayaran.setForeground(new java.awt.Color(0, 102, 51));
        btpembayaran.setText("Pembayaran");
        btpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btpembayaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btpembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btpembayaranMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_pembayaranLayout = new javax.swing.GroupLayout(pn_pembayaran);
        pn_pembayaran.setLayout(pn_pembayaranLayout);
        pn_pembayaranLayout.setHorizontalGroup(
            pn_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pembayaranLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(19, 19, 19)
                .addComponent(btpembayaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_pembayaranLayout.setVerticalGroup(
            pn_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_pembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btpembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_jadwal.setBackground(new java.awt.Color(255, 255, 255));

        pn_line6.setBackground(new java.awt.Color(255, 255, 255));
        pn_line6.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line6Layout = new javax.swing.GroupLayout(pn_line6);
        pn_line6.setLayout(pn_line6Layout);
        pn_line6Layout.setHorizontalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line6Layout.setVerticalGroup(
            pn_line6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Health Graph.png"))); // NOI18N

        btjadwal.setBackground(new java.awt.Color(255, 255, 255));
        btjadwal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btjadwal.setForeground(new java.awt.Color(0, 102, 51));
        btjadwal.setText("Penilaian & Raport");
        btjadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btjadwalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btjadwalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btjadwalMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_jadwalLayout = new javax.swing.GroupLayout(pn_jadwal);
        pn_jadwal.setLayout(pn_jadwalLayout);
        pn_jadwalLayout.setHorizontalGroup(
            pn_jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_jadwalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(19, 19, 19)
                .addComponent(btjadwal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_jadwalLayout.setVerticalGroup(
            pn_jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_jadwalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_jadwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(pn_line6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btjadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        laporan.setBackground(new java.awt.Color(255, 255, 255));
        laporan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Scroll_1.png"))); // NOI18N
        laporan.setText("LAPORAN");

        pn_absen.setBackground(new java.awt.Color(255, 255, 255));

        pn_line9.setBackground(new java.awt.Color(255, 255, 255));
        pn_line9.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line9Layout = new javax.swing.GroupLayout(pn_line9);
        pn_line9.setLayout(pn_line9Layout);
        pn_line9Layout.setHorizontalGroup(
            pn_line9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line9Layout.setVerticalGroup(
            pn_line9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btabsen.setBackground(new java.awt.Color(255, 255, 255));
        btabsen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btabsen.setForeground(new java.awt.Color(0, 102, 51));
        btabsen.setText("Lap. Santri");
        btabsen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btabsenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btabsenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btabsenMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_absenLayout = new javax.swing.GroupLayout(pn_absen);
        pn_absen.setLayout(pn_absenLayout);
        pn_absenLayout.setHorizontalGroup(
            pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_absenLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btabsen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_absenLayout.setVerticalGroup(
            pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_absenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_absenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pn_line9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btabsen, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_nilai.setBackground(new java.awt.Color(255, 255, 255));

        pn_line10.setBackground(new java.awt.Color(255, 255, 255));
        pn_line10.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line10Layout = new javax.swing.GroupLayout(pn_line10);
        pn_line10.setLayout(pn_line10Layout);
        pn_line10Layout.setHorizontalGroup(
            pn_line10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line10Layout.setVerticalGroup(
            pn_line10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btnilai.setBackground(new java.awt.Color(255, 255, 255));
        btnilai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnilai.setForeground(new java.awt.Color(0, 102, 51));
        btnilai.setText("Lap. Pembayaran");
        btnilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnilaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnilaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnilaiMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_nilaiLayout = new javax.swing.GroupLayout(pn_nilai);
        pn_nilai.setLayout(pn_nilaiLayout);
        pn_nilaiLayout.setHorizontalGroup(
            pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nilaiLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnilai)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_nilaiLayout.setVerticalGroup(
            pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_nilaiLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pn_nilaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnilai, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_line10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_keluar.setBackground(new java.awt.Color(255, 255, 255));

        pn_line11.setBackground(new java.awt.Color(255, 255, 255));
        pn_line11.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line11Layout = new javax.swing.GroupLayout(pn_line11);
        pn_line11.setLayout(pn_line11Layout);
        pn_line11Layout.setHorizontalGroup(
            pn_line11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line11Layout.setVerticalGroup(
            pn_line11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logout Rounded.png"))); // NOI18N

        btkeluar.setBackground(new java.awt.Color(255, 255, 255));
        btkeluar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btkeluar.setForeground(new java.awt.Color(153, 0, 0));
        btkeluar.setText("KELUAR");
        btkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btkeluarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btkeluarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btkeluarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_keluarLayout = new javax.swing.GroupLayout(pn_keluar);
        pn_keluar.setLayout(pn_keluarLayout);
        pn_keluarLayout.setHorizontalGroup(
            pn_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_keluarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(10, 10, 10)
                .addComponent(btkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_keluarLayout.setVerticalGroup(
            pn_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_keluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_keluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(pn_line11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_keluarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btkeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_pemb.setBackground(new java.awt.Color(255, 255, 255));

        pn_line12.setBackground(new java.awt.Color(255, 255, 255));
        pn_line12.setForeground(new java.awt.Color(0, 153, 51));

        javax.swing.GroupLayout pn_line12Layout = new javax.swing.GroupLayout(pn_line12);
        pn_line12.setLayout(pn_line12Layout);
        pn_line12Layout.setHorizontalGroup(
            pn_line12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pn_line12Layout.setVerticalGroup(
            pn_line12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        btnpembayaran.setBackground(new java.awt.Color(255, 255, 255));
        btnpembayaran.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpembayaran.setForeground(new java.awt.Color(0, 102, 51));
        btnpembayaran.setText("Lap. Penilaian");
        btnpembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpembayaranMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpembayaranMouseExited(evt);
            }
        });

        javax.swing.GroupLayout pn_pembLayout = new javax.swing.GroupLayout(pn_pemb);
        pn_pemb.setLayout(pn_pembLayout);
        pn_pembLayout.setHorizontalGroup(
            pn_pembLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pembLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pn_line12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnpembayaran)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        pn_pembLayout.setVerticalGroup(
            pn_pembLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_pembLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pn_pembLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pn_line12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pn_kiriLayout = new javax.swing.GroupLayout(pn_kiri);
        pn_kiri.setLayout(pn_kiriLayout);
        pn_kiriLayout.setHorizontalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pn_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_santri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_ustd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_kelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_jadwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pn_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(pn_kiriLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel5)))))
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(proses))
                            .addGroup(pn_kiriLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(laporan)
                                    .addComponent(pn_nilai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pn_absen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pn_pemb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pn_kiriLayout.setVerticalGroup(
            pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_kiriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(pn_kiriLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_santri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_ustd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(proses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_jadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_absen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_pemb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        getContentPane().add(pn_kiri, java.awt.BorderLayout.LINE_START);

        pn_kanan.setBackground(new java.awt.Color(255, 255, 255));
        pn_kanan.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1266, 70));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pn_kanan.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pn_dasar.setBackground(new java.awt.Color(204, 255, 255));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg3.jpg"))); // NOI18N
        pn_utama.add(jLabel14, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pn_kanan.add(pn_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(pn_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btdashbordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdashbordMouseEntered
        pn_main.setBackground(new Color(235,235,235));
        pn_line.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btdashbordMouseEntered

    private void btdashbordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdashbordMouseExited
     pn_main.setBackground(new Color(255,255,255));
     pn_line.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btdashbordMouseExited

    private void btdashbordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btdashbordMouseClicked
      pn_main.setBackground(new Color(235,235,235));
      pn_line.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuDashbord());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btdashbordMouseClicked

    private void btsantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsantriMouseClicked
      pn_santri.setBackground(new Color(235,235,235));
      pn_line1.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuSantri());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btsantriMouseClicked

    private void btsantriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsantriMouseEntered
        pn_santri.setBackground(new Color(235,235,235));
        pn_line1.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btsantriMouseEntered

    private void btsantriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsantriMouseExited
        pn_santri.setBackground(new Color(255,255,255));
        pn_line1.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btsantriMouseExited

    private void btustdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btustdMouseClicked
      pn_ustd.setBackground(new Color(235,235,235));
      pn_line2.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuUstad());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btustdMouseClicked

    private void btustdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btustdMouseEntered
      pn_ustd.setBackground(new Color(235,235,235));
      pn_line2.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btustdMouseEntered

    private void btustdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btustdMouseExited
        pn_ustd.setBackground(new Color(255,255,255));
        pn_line2.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btustdMouseExited

    private void btkelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkelasMouseClicked
      pn_kelas.setBackground(new Color(235,235,235));
      pn_line3.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuKelas());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btkelasMouseClicked

    private void btkelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkelasMouseEntered
        pn_kelas.setBackground(new Color(235,235,235));
        pn_line3.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btkelasMouseEntered

    private void btkelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkelasMouseExited
        pn_kelas.setBackground(new Color(255,255,255));
        pn_line3.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btkelasMouseExited

    private void btpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btpembayaranMouseClicked
      pn_pembayaran.setBackground(new Color(235,235,235));
      pn_line5.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new MenuPembayaran());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btpembayaranMouseClicked

    private void btpembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btpembayaranMouseEntered
        pn_pembayaran.setBackground(new Color(235,235,235));
        pn_line5.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btpembayaranMouseEntered

    private void btpembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btpembayaranMouseExited
        pn_pembayaran.setBackground(new Color(255,255,255));
        pn_line5.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btpembayaranMouseExited

    private void btjadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btjadwalMouseClicked
      pn_jadwal.setBackground(new Color(235,235,235));
      pn_line6.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new Nilai());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btjadwalMouseClicked

    private void btjadwalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btjadwalMouseEntered
        pn_jadwal.setBackground(new Color(235,235,235));
        pn_line6.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btjadwalMouseEntered

    private void btjadwalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btjadwalMouseExited
        pn_jadwal.setBackground(new Color(255,255,255));
        pn_line6.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btjadwalMouseExited

    private void btabsenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btabsenMouseClicked
      pn_absen.setBackground(new Color(235,235,235));
      pn_line9.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new LaporanAlternatif());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btabsenMouseClicked

    private void btabsenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btabsenMouseEntered
        pn_absen.setBackground(new Color(235,235,235));
        pn_line9.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btabsenMouseEntered

    private void btabsenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btabsenMouseExited
        pn_absen.setBackground(new Color(255,255,255));
        pn_line9.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btabsenMouseExited

    private void btnilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnilaiMouseClicked
      pn_nilai.setBackground(new Color(235,235,235));
      pn_line10.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new LaporanPembayaran());
      pn_utama.repaint();
      pn_utama.revalidate();
    }//GEN-LAST:event_btnilaiMouseClicked

    private void btnilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnilaiMouseEntered
        pn_nilai.setBackground(new Color(235,235,235));
        pn_line10.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btnilaiMouseEntered

    private void btnilaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnilaiMouseExited
        pn_nilai.setBackground(new Color(255,255,255));
        pn_line10.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnilaiMouseExited

    private void btkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkeluarMouseClicked
      
     int a=JOptionPane.showConfirmDialog(this, "Apakah yakin anda ingin Keluar ?",
             "Konfirmasi",JOptionPane.YES_NO_OPTION);
     if(a==0){
      dispose();
      new MenuLogin().setVisible(true);
     }
    }//GEN-LAST:event_btkeluarMouseClicked

    private void btkeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkeluarMouseEntered
        pn_keluar.setBackground(new Color(235,235,235));
        pn_line11.setBackground(new Color(153,0,0));
    }//GEN-LAST:event_btkeluarMouseEntered

    private void btkeluarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btkeluarMouseExited
       pn_keluar.setBackground(new Color(255,255,255));
       pn_line11.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btkeluarMouseExited

    private void btnpembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpembayaranMouseClicked
      pn_pemb.setBackground(new Color(235,235,235));
      pn_line12.setBackground(new Color(0,204,102));  
      
      pn_utama.removeAll();
      pn_utama.add(new LaporanNilai());
      pn_utama.repaint();
      pn_utama.revalidate();
    
    }//GEN-LAST:event_btnpembayaranMouseClicked

    private void btnpembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpembayaranMouseEntered
        pn_pemb.setBackground(new Color(235,235,235));
        pn_line12.setBackground(new Color(0,204,102));
    }//GEN-LAST:event_btnpembayaranMouseEntered

    private void btnpembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpembayaranMouseExited
        pn_pemb.setBackground(new Color(255,255,255));
        pn_line12.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnpembayaranMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtamaDS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtamaDS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btabsen;
    private javax.swing.JLabel btdashbord;
    private javax.swing.JLabel btjadwal;
    private javax.swing.JLabel btkelas;
    private javax.swing.JLabel btkeluar;
    private javax.swing.JLabel btnilai;
    private javax.swing.JLabel btnpembayaran;
    private javax.swing.JLabel btpembayaran;
    private javax.swing.JLabel btsantri;
    private javax.swing.JLabel btustd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel laporan;
    private javax.swing.JPanel pn_absen;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JPanel pn_jadwal;
    private javax.swing.JPanel pn_kanan;
    private javax.swing.JPanel pn_kelas;
    private javax.swing.JPanel pn_keluar;
    private javax.swing.JPanel pn_kiri;
    private javax.swing.JPanel pn_line;
    private javax.swing.JPanel pn_line1;
    private javax.swing.JPanel pn_line10;
    private javax.swing.JPanel pn_line11;
    private javax.swing.JPanel pn_line12;
    private javax.swing.JPanel pn_line2;
    private javax.swing.JPanel pn_line3;
    private javax.swing.JPanel pn_line5;
    private javax.swing.JPanel pn_line6;
    private javax.swing.JPanel pn_line9;
    private javax.swing.JPanel pn_main;
    private javax.swing.JPanel pn_nilai;
    private javax.swing.JPanel pn_pemb;
    private javax.swing.JPanel pn_pembayaran;
    private javax.swing.JPanel pn_santri;
    private javax.swing.JPanel pn_ustd;
    private javax.swing.JPanel pn_utama;
    private javax.swing.JLabel proses;
    // End of variables declaration//GEN-END:variables
}
