/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Nanang M32
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnmenu = new javax.swing.JPanel();
        conten = new javax.swing.JPanel();
        pnutama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        navbar.setBackground(new java.awt.Color(51, 255, 51));
        navbar.setPreferredSize(new java.awt.Dimension(898, 70));

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(navbar, java.awt.BorderLayout.PAGE_START);

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(200, 444));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        pnmenu.setPreferredSize(new java.awt.Dimension(250, 444));
        pnmenu.setLayout(new javax.swing.BoxLayout(pnmenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnmenu);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        getContentPane().add(sidebar, java.awt.BorderLayout.LINE_START);

        conten.setBackground(new java.awt.Color(255, 255, 255));

        pnutama.setBackground(new java.awt.Color(255, 255, 255));
        pnutama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout contenLayout = new javax.swing.GroupLayout(conten);
        conten.setLayout(contenLayout);
        contenLayout.setHorizontalGroup(
            contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contenLayout.setVerticalGroup(
            contenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(conten, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(916, 561));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel conten;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel pnmenu;
    private javax.swing.JPanel pnutama;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        // untuk menambahkan icon di sedbar
        ImageIcon iconMaster     = new ImageIcon(getClass().getResource("/img/home.png"));
        ImageIcon iconDatasantri = new ImageIcon(getClass().getResource("/img/santri.png"));
        ImageIcon iconGuru       = new ImageIcon(getClass().getResource("/img/guru.png"));
        ImageIcon iconDsantri = new ImageIcon(getClass().getResource("/img/dsantri1.png"));
        ImageIcon iconTsantri = new ImageIcon(getClass().getResource("/img/tsantri.png"));
        
        
        //didalam master Data Santri
        MenuItem masDatasantri1 = new MenuItem(null, true, iconDsantri,"Data Santri",null);
        MenuItem masDatasantri2 = new MenuItem(null, true, iconTsantri,"Tambah Santri",null);
        
        MenuItem masDataguru1 = new MenuItem(null, true, iconDsantri,"Data Santri",null);
        MenuItem masDataguru2 = new MenuItem(null, true, iconTsantri,"Tambah Santri",null);
        
        // memanggil sedbar dengan iconenya
        MenuItem menuMaster = new MenuItem(iconMaster,false,null,"DASBOARD",null);
        MenuItem menuDatasantri = new MenuItem(iconDatasantri,false,null,"Santri",null,masDatasantri1,masDatasantri2);
        MenuItem menuDataguru = new MenuItem(iconGuru,false,null,"Guru",null,masDataguru1,masDataguru2);
        
        // menampilkan sidbar
        addMenu(menuMaster,menuDatasantri,menuDataguru);
    }
    
    private void addMenu (MenuItem...menu){
        for (int i=0;i <menu.length; i++) {
            pnmenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getsubMenu();
            for (MenuItem m : subMenu){
                addMenu(m);
            }
        }
        pnmenu.revalidate();
     }
}
