/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;

/**
 *
 * @author Nanang M32
 */
public class MenuItem extends javax.swing.JPanel {

    public ArrayList<MenuItem> getsubMenu(){
        return subMenu;
    }
    
   private final ArrayList<MenuItem> subMenu = new ArrayList<>();
   
   private ActionListener act;
   
    /**
     *
     */
    public MenuItem(Icon icon, boolean sbm, Icon iconSub, String menuName, ActionListener act,MenuItem... subMenu) {
        initComponents();
        
        lbicon.setIcon(icon);
        lbmenu.setText(menuName);
        lbiconsub.setIcon(iconSub);
        lbiconsub.setVisible(sbm);
        
        if (act !=null){
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE,45));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE,45));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE,45));
        for (int i = 0; i < subMenu.length; i++){
            this.subMenu.add(subMenu[i]);
            subMenu[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbmenu = new javax.swing.JLabel();
        lbiconsub = new javax.swing.JLabel();
        lbicon = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lbmenu.setText("Menu Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbicon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbiconsub, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(lbicon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbiconsub, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    
        if (showing){
         hideMenu();
     }else {
         showMenu();
     }
     if (act !=null){
         act.actionPerformed(null);
     }
    }//GEN-LAST:event_formMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbicon;
    private javax.swing.JLabel lbiconsub;
    private javax.swing.JLabel lbmenu;
    // End of variables declaration//GEN-END:variables

    private void showMenu() {
        new Thread (new Runnable(){
         @Override
         public void run(){
             for (int i = 0;i< subMenu.size(); i++){
                 sleep();
                 subMenu.get(i).setVisible(true);
             }
             showing = true;
             getParent().repaint();
             getParent().revalidate();
         }
        }).start();
    }

    private void hideMenu() {
        new Thread (new Runnable(){
         @Override
         public void run(){
             for (int i = subMenu.size()-1; i >=0; i--){
                 sleep();
                 subMenu.get(i).setVisible(true);
                 subMenu.get(i).hideMenu();
             }
             getParent().repaint();
             getParent().revalidate();
             showing = false;
    }
 }).start();
    }
    
private void sleep(){
    try{
        Thread.sleep(20);
    }catch(Exception e){
    }
   }
}
